import {
  Users,
  ShieldCheck,
  LogOut,
  Menu,
  Bell,
  LayoutDashboard,
  BookOpen,
  UserCheck,
  ChevronRight,
  Sparkles,
  Package,
  DollarSign,
  BarChart3,
  AlertTriangle,
  TrendingUp,
  ArrowUpRight,
  Activity,
  GraduationCap,
} from "lucide-react";

export const ADMIN_ICONS = {
  USERS: Users,
  SHIELD: ShieldCheck,
  LOGOUT: LogOut,
  MENU: Menu,
  BELL: Bell,
  LAYOUTDASHBOARD: LayoutDashboard,
  BOOKOPEN: BookOpen,
  USERCHECK: UserCheck,
  CHEVRONRIGHT: ChevronRight,
  SPARKLES: Sparkles,
  PACKAGE: Package,
  DOLLARSIGN: DollarSign,
  BARCHART3: BarChart3,
  ALERT: AlertTriangle,
  TRENDINGUP: TrendingUp,
  ARROWUPRIGHT: ArrowUpRight,
  ACTIVITY: Activity,
  GRADUATIONCAP: GraduationCap,
};
